# -*- coding: utf-8 -*-
"""Spam Comments Detectionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12itppynWvYLIrXvffa4HUVfxCCmhrbYt
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

data=pd.read_csv("/content/Youtube01-Psy.csv")

data.head()

data=data[["CONTENT","CLASS"]]

data.sample(6)

data['CLASS']=data["CLASS"].map({0:"Not Spam",1:"Spam"})

data.sample(6)

x=np.array(data["CONTENT"])
y=np.array(data["CLASS"])

cv=CountVectorizer()
x=cv.fit_transform(x)
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)
model=BernoulliNB()

model.fit(xtrain,ytrain)

print(model.score(xtrain,ytrain))

#checking the spam
sample = "hii llike share my post  "
data = cv.transform([sample]).toarray()
print(model.predict(data))

